import pprint as pprint


def test_osb_converter():
    import src.common.osb_converter as ut

    test_sb = [{"type": "Sprite",
                "filepath": "sb/background.png",
                "layer": "Background",
                "tether": "Centre",
                "position": [320, 240],
                "functions": [{"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390}]},
               {"type": "Sprite",
                "filepath": "sb/background.png",
                "layer": "Background",
                "tether": "Centre",
                "position": [320, 240],
                "functions": [{"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390}]},
               {"type": "Sprite",
                "filepath": "sb/background.png",
                "layer": "Background",
                "tether": "Centre",
                "position": [320, 240],
                "functions": [{"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390}]},
               {"type": "Sprite",
                "filepath": "sb/background.png",
                "layer": "Background",
                "tether": "Centre",
                "position": [320, 240],
                "functions": [{"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390}]},
               {"type": "Sprite",
                "filepath": "sb/background.png",
                "layer": "Background",
                "tether": "Centre",
                "position": [320, 240],
                "functions": [{"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390}]},
               {"type": "Sprite",
                "filepath": "sb/background.png",
                "layer": "Foreground",
                "tether": "Centre",
                "position": [320, 240],
                "functions": [{"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390},
                              {"function": "S",
                               "easing": "1",
                               "start": 12032,
                               "end": 12390}]}]

    # print(ut.convert_storyboard_to_osb(test_sb))

    test = ut.convert_osb_element_to_object("""Sprite,Background,Centre,"mosbg.jpg",320,240\n F,0,0,,0""")

    assert ut.convert_storyboard_to_osb(test_sb)
